#!/usr/bin/env php
<?php
/**
 *
 * CLI tool to quickly test/debug specific API methods.
 *
 */

// composer auto loader
use Lodestone\Enum\LocaleEnum;

require __DIR__ . '/vendor/autoload.php';

$api = new \Lodestone\Api();
$exporter = new \LodestoneUtils\Exporter();

//print_r($argv);

if ($argc < 2) {
    print("No arguments provided.\n");
    return;
}

// Remove the cli file from the arguments array
array_shift($argv);
$cliCommandType = $argv[0];

$locale = LocaleEnum::EN->value;

foreach ($argv as $key => $arg) {
    if ($arg === "-l") {
        if (
            !isset($argv[$key + 1])
            || !LocaleEnum::isValid(strtolower($argv[$key + 1]))
        ) {
            print_r("INVALID ARGUMENT: Expected country identifier or wrong country identifier\n");
            exit(1);
        }
        $locale = strtolower($argv[$key + 1]);
        break;
    }
}

switch ($cliCommandType) {
    case "character":
        if (!isset($argv[1])) {
            print_r("INVALID ARGUMENT: Expected Character ID\n");
            break;
        }
        print_r("Parsing character of {$argv[1]}...\n");
        $results = $api->character()->get($argv[1], $locale);
        if (isset($argv[2]) == "-f") {
            $exporter->exportToFile($argv[0], $argv[3], $results);
            break;
        }
        print_r($results);
        break;

    case "characterfull":
        if (!isset($argv[1])) {
            print_r("INVALID ARGUMENT: Expected Character ID\n");
            break;
        }
        print_r("Parsing character of {$argv[1]}...\n");
        $results = $api->character()->getFull($argv[1], $locale, true);
        if (isset($argv[2]) == "-f") {
            $exporter->exportToFile($argv[0], $argv[3], $results);
            break;
        }
        print_r($results);
        break;

    case "freecompany":
        if (!isset($argv[1])) {
            print_r("INVALID ARGUMENT: Expected FreeCompany ID\n");
            break;
        }
        print_r("Parsing freecompany of {$argv[1]}...\n");
        $results = $api->freecompany()->get($argv[1], $locale);
        if (isset($argv[2]) == "-f") {
            $exporter->exportToFile($argv[0], $argv[3], $results);
            break;
        }
        print_r($results);
        break;

    case "pvpteam":
        if (!isset($argv[1])) {
            print_r("INVALID ARGUMENT: Expected PVP Team ID\n");
            break;
        }
        print_r("Parsing pvp team of {$argv[1]}...\n");
        $results = $api->pvpteam()->get($argv[1], $locale);
        if (isset($argv[2]) == "-f") {
            $exporter->exportToFile($argv[0], $argv[3], $results);
            break;
        }
        print_r($results);
        break;

    case "linkshell":
        if (!isset($argv[1])) {
            print_r("INVALID ARGUMENT: Expected Linkshell ID\n");
            break;
        }
        print_r("Parsing linkshell of {$argv[1]}...\n");
        $results = $api->linkshell()->get(id: $argv[1], locale: $locale)->Results;
        if (isset($argv[2]) == "-f") {
            $exporter->exportToFile($argv[0], $argv[3], $results);
            break;
        }
        print_r($results);
        break;

    case "cwlinkshell":
        if (!isset($argv[1])) {
            print_r("INVALID ARGUMENT: Expected Linkshell ID\n");
            break;
        }
        print_r("Parsing linkshell of {$argv[1]}...\n");
        $results = $api->linkshell()->getCrossWorld(id: $argv[1], locale: $locale)->Results;
        if (isset($argv[2]) == "-f") {
            $exporter->exportToFile($argv[0], $argv[3], $results);
            break;
        }
        print_r($results);
        break;

    case "achievements":
        if (!isset($argv[1])) {
            print_r("INVALID ARGUMENT: Expected Linkshell ID\n");
            break;
        }
        print_r("Parsing achievements of {$argv[1]}...\n");
        $results = $api->character()->achievements(id: $argv[1], locale: $locale);
        if (isset($argv[2]) == "-f") {
            $exporter->exportToFile($argv[0], $argv[3], $results);
            break;
        }
        print_r($results);
        break;

    case "banners":
        $results = $api->lodestone()->banners();
        if (isset($argv[1]) == "-f") {
            $exporter->exportToFile($argv[0], $argv[2], $results);
            break;
        }
        print_r($results);
        break;

    case "leaderboards":
        // Don't @me I know this is scuff.
        switch ($argv[1]) {
            case "feast":
                $results = $api->leaderboards()->feast();
                if (isset($argv[2]) == "-f") {
                    $exporter->exportToFile($argv[0], $argv[3], $results);
                    break;
                }
                print_r($results);
                break;

            case "potd":
                $results = $api->leaderboards()->ddPalaceOfTheDead();
                if (isset($argv[2]) == "-f") {
                    $exporter->exportToFile($argv[0], $argv[3], $results);
                    break;
                }
                print_r($results);
                break;

            case "hoh":
                $results = $api->leaderboards()->ddHeavenOnHigh();
                if (isset($argv[2]) == "-f") {
                    $exporter->exportToFile($argv[0], $argv[3], $results);
                    break;
                }
                print_r($results);
                break;
        }
}
